apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-example
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/manifests
    repoURL: https://github.com/tracker-tv/argocd-example
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
